INSERT INTO AEROLINEA (NOMBRE) VALUES ('birdarilnes');
INSERT INTO AEROLINEA (NOMBRE) VALUES ('runair');
INSERT INTO AVION (FK_AEROLINEA_ID,CAPACIDAD,MODELO) VALUES (1,150,'Boeing 737');
INSERT INTO AVION (FK_AEROLINEA_ID,CAPACIDAD,MODELO) VALUES (1,200,'Airbus A320');
INSERT INTO AVION (FK_AEROLINEA_ID,CAPACIDAD,MODELO) VALUES (1,100,'Airbus 300');
INSERT INTO AVION (FK_AEROLINEA_ID,CAPACIDAD,MODELO) VALUES (1,300,'Airbus 600');
INSERT INTO AVION (FK_AEROLINEA_ID,CAPACIDAD,MODELO) VALUES (1,225,'Maverick 121');
